### ISSUE TITLE
Need help for creating page after creating science plan.

### ISSUE THREAD

**Issue by VectorXz** [VectorXz/GeminiFive#5]
Currently, after creating the science plan, it will shown plain text "added!"

I need someone to create a beautiful page showing success text by using the current template.

Someone please do this! Thanks!

![Screenshot_9](https://user-images.githubusercontent.com/9075013/83973013-b8e66f80-a90d-11ea-831f-ea24508752ac.png)

**Comment by VectorXz** [comment]
However, if you're interesting in doing this, please comment below. So others people will not duplicate your work!

**Comment by maijsp** [comment]
I did it
